### ISSUE TITLE
Initial Tokens are all given to beneficiary on construction?

### ISSUE THREAD

**Issue by fodder1997** [batlinal/ftt#11]
I assume this is correct but comment doesn't match. I assume the intention is to issue all tokens to the beneficiary rather than to issuer first and issuer assign them to beneficiary?

```
    balances[_beneficiary] = _totalSupply; // Assign all tokens to issuer
```

**Comment by batlinal** [comment]
In the first version, indeed I am keeping it simple and assigning all tokens to the beneficiary. See https://github.com/batlinal/ftt/commit/43b6788a4a728769b052397a7e90ccb3eb0e62c9. In the future it should be possible to assign to sub-beneficiaries, see  #5.
